[package]
name = "zellen"
description = "Zellen: A cellular automata engine built on macroquad."
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3.26"
